# Generated by Django 4.1.6 on 2024-01-31 11:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('hid', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('posted_on', models.DateTimeField(default=datetime.datetime(2024, 1, 31, 16, 52, 7, 298652), editable=False)),
                ('upvotes', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('bday', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True)),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entry.newsfeed')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entry.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entry.newsfeed')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entry.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('hack_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entry.newsfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entry.profile')),
            ],
        ),
    ]
